#ifndef GUARD_PTY_BITWISE_HPP__
#define GUARD_PTY_BITWISE_HPP__

#include "properties/details/operation_macros.hpp"
#include "properties/details/bitwise_operation_macro.hpp"
#include "properties/details/define_property.hpp"
#include "properties/details/define_operator_base.hpp"
#include "properties/operators/bitwise.hpp"

namespace pty {

PTY_DETAILS_DEFINE_PROPERTY(Bitwise, 
		PTY_DETAILS_APPLY_TO_BITWISE_BINARY_CONST_OPERATIONS(PTY_DETAILS_DEFINE_BINARY_CONST_OPERATOR)
		PTY_DETAILS_APPLY_TO_BITWISE_BINARY_MUTABLE_OPERATIONS(PTY_DETAILS_DEFINE_BINARY_MUTABLE_OPERATOR)
		PTY_DETAILS_APPLY_TO_BITWISE_UNARY_OPERATIONS(PTY_DETAILS_DEFINE_UNARY_CONST_OPERATOR)
		PTY_DETAILS_DEFINE_OPERATOR_BASE(bitwise)
		)

PTY_DETAILS_APPLY_TO_TRANSITIVE_BITWISE_OPERATIONS(PTY_DETAILS_DEFINE_TRANSITIVE_OPERATOR)



}

#undef PTY_DETAILS_APPLY_TO_TRANSITIVE_BITWISE_OPERATIONS
#undef PTY_DETAILS_APPLY_TO_BITWISE_BINARY_CONST_OPERATIONS
#undef PTY_DETAILS_APPLY_TO_BITWISE_BINARY_MUTABLE_OPERATIONS

#endif
