#ifndef GUARD_PTY_COMPARABLE_HPP__
#define GUARD_PTY_COMPARABLE_HPP__

#include "details/operation_macros.hpp"
#include "details/define_property.hpp"

#define PTY_DETAILS_APPLY_TO_COMPARISON_OPERATORS(fun) \
	fun(<, less)\
	fun(<=, less_equal)\
	fun(>, greater)\
	fun(>=, greater_equal)\
	fun(==, equal_to)\
	fun(!=, not_equal_to)

#define PTY_DETAILS_APPLY_TO_TRANSITIVE_COMPARISON_OPERATORS(fun) \
	fun(==, Comparable) \
	fun(!=, Comparable)

#define PTY_DETAILS_APPLY_TO_REVERSABLE_COMPARISON_OPERATORS(fun) \
	fun(<, >, Comparable) \
	fun(>, <, Comparable) \
	fun(<=, >=, Comparable) \
	fun(>=, <=, Comparable) \


namespace pty {

	PTY_DETAILS_APPLY_TO_COMPARISON_OPERATORS(PTY_DETAILS_DEFINE_BINARY_CONST_OPERATION) 

	PTY_DETAILS_DEFINE_PROPERTY(Comparable,

		PTY_DETAILS_APPLY_TO_COMPARISON_OPERATORS(PTY_DETAILS_DEFINE_BINARY_CONST_OPERATOR)

		)

	PTY_DETAILS_APPLY_TO_TRANSITIVE_COMPARISON_OPERATORS(PTY_DETAILS_DEFINE_TRANSITIVE_OPERATOR)
	PTY_DETAILS_APPLY_TO_REVERSABLE_COMPARISON_OPERATORS(PTY_DETAILS_DEFINE_REVERSE_OPERATOR)
}

#undef PTY_DETAILS_APPLY_TO_COMPARISON_OPERATORS
#undef PTY_DETAILS_APPLY_TO_TRANSITIVE_COMPARISON_OPERATORS
#undef PTY_DETAILS_APPLY_TO_REVERSABLE_COMPARISON_OPERATORS

#endif
